# Generated by Django 2.0.6 on 2018-07-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20180703_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='refresh_token_token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
