# Generated by Django 2.0.6 on 2018-07-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180703_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='refresh_token_token',
            new_name='refresh_token',
        ),
    ]
